version: '3'
services:
  apache2:
    image: ${REGISTRY_HOSTNAME}:${REGISTRY_PUBLISHED_PORT}/web2py_apache2
    deploy:
      replicas: 3
# placeholder - future extension to constraint web tier, if needed
#      placement:
#        constraints:
#        - node.labels.web2py.tier.web==true
    ports: 
      - "80:8080"
    volumes:
      - ${APACHE2_CONF_DIR}:/usr/local/apache2/conf
      - ${APACHE2_HTDOCS_DIR}:/usr/local/apache2/htdocs
  python27:
    image: ${REGISTRY_HOSTNAME}:${REGISTRY_PUBLISHED_PORT}/web2py_python27
    deploy:
      replicas: 3
# placeholder - future extension to contraint app tier, if needed
#      placement:
#        constraints:
#        - node.labels.web2py.tier.app==true
    ports:
      - "8080:80"
  mysql5:
    image: ${REGISTRY_HOSTNAME}:${REGISTRY_PUBLISHED_POST}/web2py_mysql5
    deploy:
      placement:
        constraints:
        - node.labels.web2py.tier.db==true
    ports:
      - "3306:3306"
    volumes:
      - ${MYSQL_CONF_DIR}:/etc/mysql/mysql.conf.d
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ${MYSQL_INIT_DIR}:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: Welcome1


